# Generated by Django 2.2.1 on 2019-05-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='building',
            field=models.TextField(blank=True, null=True, verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='office',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='long',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Longitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='postcode',
            field=models.CharField(default=0, max_length=5, verbose_name='Postcode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='street',
            field=models.TextField(default=0, verbose_name='Street'),
            preserve_default=False,
        ),
    ]
