# Generated by Django 2.2.1 on 2019-05-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190524_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='office',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Street'),
        ),
    ]
