# Generated by Django 2.2.1 on 2019-05-24 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190524_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='City ID')),
                ('city_name', models.CharField(max_length=50, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Province ID')),
                ('province_name', models.CharField(max_length=50, verbose_name='Province')),
            ],
        ),
        migrations.AlterField(
            model_name='office',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='office',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.City'),
        ),
        migrations.AddField(
            model_name='office',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Province'),
        ),
    ]
