# Generated by Django 2.2.1 on 2019-06-02 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='City ID')),
                ('city_name', models.CharField(max_length=50, verbose_name='City')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Province ID')),
                ('province_name', models.CharField(max_length=50, verbose_name='Province')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=100, verbose_name='Office Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Flag Active')),
                ('branch_id', models.IntegerField(verbose_name='Branch ID')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street')),
                ('building', models.CharField(blank=True, max_length=100, null=True, verbose_name='Building')),
                ('postcode', models.CharField(blank=True, max_length=5, null=True, verbose_name='Postcode')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offices.City')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offices.Province')),
            ],
            options={
                'ordering': ('branch_id',),
            },
        ),
    ]
