# Generated by Django 2.2.1 on 2019-06-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_auto_20190604_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='manager_pos_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.Branch'),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.Office'),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='office_status',
            field=models.CharField(blank=True, choices=[('KC', 'Kantor Cabang'), ('KCP', 'Kantor Cabang Pembantu'), ('KK', 'Kantor Kas'), ('KF', 'Kantor Fungsional'), ('Kanwil', 'Kantor Wilayah'), ('KPNO', 'Kantor Pusat Non Operasional')], max_length=6, null=True),
        ),
    ]
