# Generated by Django 2.2.1 on 2019-06-08 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('continent_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('continent_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ('country_code',),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('province_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubdivisionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Subdivision Categories',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('village_code', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('village_name', models.CharField(max_length=50)),
                ('is_village', models.BooleanField(default=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.District')),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('subdivision_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('subdivision_name', models.CharField(max_length=60)),
                ('is_recommended', models.BooleanField(default=True)),
                ('alt_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='Alternative code')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.SubdivisionCategory')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=25)),
                ('continent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Continent')),
            ],
        ),
        migrations.CreateModel(
            name='Regency',
            fields=[
                ('regency_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('regency_name', models.CharField(max_length=30)),
                ('is_city', models.BooleanField(default=False)),
                ('is_capital', models.BooleanField(default=False)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Province')),
            ],
            options={
                'verbose_name_plural': 'Regencies',
            },
        ),
        migrations.AddField(
            model_name='province',
            name='subdivision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Subdivision'),
        ),
        migrations.AddField(
            model_name='district',
            name='regency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Regency'),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Region'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=30)),
                ('is_capital', models.BooleanField(default=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Subdivision')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
