# Generated by Django 2.2.1 on 2019-06-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='id',
        ),
        migrations.AlterField(
            model_name='city',
            name='city_code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='alt_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Alternative code'),
        ),
    ]
