# Generated by Django 2.2.1 on 2019-06-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20190604_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
