# Generated by Django 2.2.1 on 2019-06-08 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20190608_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='province_name',
        ),
    ]
